### ISSUE TITLE
Improve efficiency of KdlVectorConverter

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#41]
Though computational cost is not so much of an issue nowadays, the current string comparison implementation of KdlVectorConverter vectorToFrame() and frameToVector() could be rendered more efficient in many ways. Since we're in C++, I'd be thinking in polymorphism, but even a simple pointer to a function would be better than the current implementation.

**Comment by PeterBowman** [comment]
Possibly superseded by #113.

**Comment by PeterBowman** [comment]
Closing as invalid due to #114. Logic for selection of angle representations has been transferred to [KinematicRepresentation.cpp](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/0ff88b2110b1bba691457a2f67136410e9c34c3e/libraries/KinematicRepresentationLib/KinematicRepresentation.cpp) and it's no longer based on string comparisons; rather, we've moved to using enums.
