### ISSUE TITLE
Need functional collision avoidance module

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#63]
Started work on C++ teoCollisionAvoidance, but may be more practical to do in Python.

**Comment by RaulFdzbis** [comment]
Some advances have been made in this area. Some problems and solutions have been found working in this issue. The followings are:
**Good things**
- **The initial [idea](http://openrave-users-list.185357.n3.nabble.com/Feature-Announcement-Automated-Convex-Decomposition-for-Collision-Meshes-td186409.html) behind ConvexDecompositions was to be used for collision checks, just as we wanna do**. So thats good, i guess. 
- If we want to set the cdmodel parameters, the **generate**(**kwargs) function should be used instead the autogenerate function used in the [checkconvexdecomposition example](http://openrave.org/docs/0.8.2/openravepy/examples.checkconvexdecomposition/). This function is used in our [code](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L33) to set the padding value of our model.
-  A **CheckConvexDecomposition** [test](https://github.com/roboticslab-uc3m/teo-main/blob/8426dc81cd7a5b28e6b2736ba9eac4033935e4d6/python/teoCollisionAvoidance/test/test.py) based on the one used in this [example](http://openrave.org/docs/0.8.2/openravepy/examples.checkconvexdecomposition/) was performed. Initially all the tested points were returned as points inside the convexmodel. The picture below is one of the results of this initals experiments. This result showed us there was some problem with the generated cdmodel. 
  ![teo_cd_padding_bad_check](https://cloud.githubusercontent.com/assets/6704441/19602526/d31fd8c0-97ad-11e6-8d57-8dbce867bf50.png)
  This problem was later solved setting some padding to the cdmodel using the [generate](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L33) function.
  ![teo_cd_padding_001_check](https://cloud.githubusercontent.com/assets/6704441/19601826/18864faa-97ab-11e6-9249-4e90c7ecbcf9.png)

**Not so good things (TODO)**
- [ ] **Some of the OpenRave [examples](http://openrave.org/docs/0.8.2/examples/) do not work properly** using ubuntu 14.04. So far these problems are only presented in the examples using robots different than the barrettwam robot used [here](http://openrave.org/docs/0.8.2/openravepy/examples.checkconvexdecomposition/). Some similar [issue](http://openrave-users-list.185357.n3.nabble.com/Errors-when-i-execute-python-examples-td4027742.html) have already been reported, however no solution have been found yet. Since this is not critical for the resolution of this issue, **this is not a priority.**
- [x] When the convex decomposition model (cdmdel) is generated, this cdmodel is [saved](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L38) in the openrave database as a function of it's geometry. This means that if some padding is done in the cdmodel, the geometry changes and therefore its name. This is an already reported [behaviour](http://openrave-users-list.185357.n3.nabble.com/Re-Hand-Jacobian-td3506786.html) in OpenRave. **At the end, this implies that a new model have to be generated everytime we want to work with a padded model.** The [load](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L30) function doesn't work. 
  To solve this problem, the temporal solution is to (since the "load" function always load the not padded cdmodel) to manually rename the padded model to have the same as the not padded one. 
- [x] **Checkselfcollision() does not work in the experiments done with the TEO cdmodel**. These experiments consisted on using a large padding value to force the cdmodel to have some selfcollision without the need of moving the robot. Below is a picture example of the resulting cdmodel. Different padding values have been tested. However no selfcollision was detected. 
  SelfCollision function was called in two different ways, directly using the robot variable loaded in openrave in two scenarios (with and without [cdmodel.setrobot()](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L46)), and using the robot variable referenced in the cdmodel class this means cdmodel.robot.checkselfcollision(), without success. No collision were detected in any of the cases. As a note there is an [open issue ](https://github.com/rdiankov/openrave/issues/118) in openrave, with the goal of disable selfcollision using cdmodels. However is an OPEN issue, so it should not be implemented. Further study should be done in this direction.
  ![teo_cd_padding_01](https://cloud.githubusercontent.com/assets/6704441/19602196/97917f26-97ac-11e6-8eb9-dbc1b114ac55.png)
- [x] I am not yet sure of how to use and how [setrobot()](http://openrave.org/docs/0.8.2/_modules/openravepy/databases/convexdecomposition/#ConvexDecompositionModel.setrobot) function works. Maybe this is behind why checkselfcollision does not work.
- [ ] When a cdmodel.show() is executed in the code, the execution of the rest of the program stops. Is this normal?

_At this moment the direction of the work done in this issue is to be able to perform a checkselfcollision test using the cdmodel. However this is not as critital as could seem. The reason is because there are many other ways to do a padding in the robot model. This could be done manually changing the xml file of the robot (rude way of doing things), or creating some new trimesh and assign it to the robot collision mesh (something similar as what is done in CD). However right now the best option still is to use the convexdecomposition module. So some more work should be done in this direction._

**Comment by RaulFdzbis** [comment]
**Update 1: How setrobot() works**
After some experiments the conclusion is that the [setrobot()](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L46) function is in charge to assign the collisionmesh generated with the ConvexDecomposition module to the xml robot. 

This means that in our tests the collisionmesh is changed to the convexdecomposition model. However, the [selfcollision function](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L55) stills not detecting the selfcollision that should appear after this padding. Some study about how the selfcollision function works should be done at this moment.

**Comment by RaulFdzbis** [comment]
**Update 2: CheckCollision test Successful**
CheckSelfcollision() was successfully tested in the new experiments. Openrave is able to detect collision using the cdmodel as the collision mesh. To test this a new experiment was performed. In this experiment instead of using high padding values, the robot was initially [moved](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L16-L21) to a collision position. Then a [checkselfcollision test](https://github.com/roboticslab-uc3m/teo-main/blob/8e4ef9beb72ce07b7594b4b4b49258b4dd39a6d6/python/teoCollisionAvoidance/test/test.py#L55-L58) is performed.

The results of these experiments show how in some positions, the robot didnt detect any self collision using the detailed model (without ConvexDecomposition). However, using a padded cdmodel in the same position the robot detected a collision. This means that the padded cdmodel is successfully generated and used for collision  checks in openrave.

**Comment by jgvictores** [comment]
Now at: https://github.com/roboticslab-uc3m/openrave-yarp-plugins

**Comment by jgvictores** [comment]
Good against simulator at https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/8704a332ad4dfd3e044f4b8ffd64d731c59c69c4

**Comment by jgvictores** [comment]
Tested and working with simulator and real robot, now only issue is to "Improve implementation and documentation for teo vs teoSim" (https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/13). Closing issue.

**Comment by jgvictores** [comment]
Reopening just to reflect state on https://github.com/roboticslab-uc3m/teo-main/projects/1 which is not at global scope of organization.

**Comment by jgvictores** [comment]
Finished at around https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/4afbb7cf2e0e81a8c4d537cc7f8c923d208aa69f.

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/openrave-yarp-plugins#84
