### ISSUE TITLE
[asr] teoBase needs a reduced dictionary to work reliably

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/kinematics-dynamics#68]
[asr] teoBase needs a reduced dictionary to work. We've been having issues since https://github.com/roboticslab-uc3m/teo-head/issues/32

**Comment by rsantos88** [comment]
I think, this issue is concluded with the new version of speechRecognition (see this closed [issue](https://github.com/roboticslab-uc3m/teo-head/issues/42)) and with separated dictionaries (see [this](https://github.com/roboticslab-uc3m/teo-head/pull/47))
Please, close it if you think is that true :)

**Comment by jgvictores** [comment]
Okay, code looks good.
I'd prefer to close this issue once we're done with https://github.com/roboticslab-uc3m/teo-head/issues/46 as this is a teoBase/teo-main issue that arose with these updates.

**Comment by rsantos88** [comment]
it's ready [:D](https://github.com/roboticslab-uc3m/teo-head/issues/46#issuecomment-258812920) !!

**Comment by jgvictores** [comment]
Cool!
